# Generated by Django 5.2.14 on 2026-05-24 21:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_analyses', models.IntegerField(default=0)),
                ('stego_detected', models.IntegerField(default=0)),
                ('clean_detected', models.IntegerField(default=0)),
                ('avg_analysis_time', models.FloatField(default=0.0)),
                ('avg_confidence', models.FloatField(default=0.0)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'db_table': 'analytics_logs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, unique=True)),
                ('model_type', models.CharField(max_length=50)),
                ('model_path', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('trained_on', models.DateTimeField()),
                ('training_samples', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'model_versions',
                'ordering': ['-trained_on'],
            },
        ),
        migrations.CreateModel(
            name='SteganographyTechnique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('detection_methods', models.JSONField()),
                ('detection_rate', models.FloatField(default=0.0)),
                ('false_positive_rate', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'steganography_techniques',
            },
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'bmp', 'tiff'])])),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField()),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('format', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'uploaded_images',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('method_used', models.CharField(max_length=50)),
                ('detected', models.BooleanField()),
                ('confidence', models.FloatField()),
                ('user_confirmed', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='backend.uploadedimage')),
            ],
            options={
                'verbose_name_plural': 'detection histories',
                'db_table': 'detection_history',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_suspicious', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField()),
                ('lsb_score', models.FloatField(default=0.0)),
                ('chi_square_score', models.FloatField(default=0.0)),
                ('rs_score', models.FloatField(default=0.0)),
                ('frequency_score', models.FloatField(default=0.0)),
                ('metadata_score', models.FloatField(default=0.0)),
                ('cnn_confidence', models.FloatField(blank=True, null=True)),
                ('cnn_prediction', models.CharField(blank=True, max_length=10, null=True)),
                ('lsb_details', models.JSONField(blank=True, null=True)),
                ('chi_square_details', models.JSONField(blank=True, null=True)),
                ('rs_details', models.JSONField(blank=True, null=True)),
                ('frequency_details', models.JSONField(blank=True, null=True)),
                ('metadata_details', models.JSONField(blank=True, null=True)),
                ('estimated_payload_size', models.FloatField(blank=True, null=True)),
                ('estimated_payload_percentage', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='backend.uploadedimage')),
            ],
            options={
                'db_table': 'analysis_results',
            },
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['user', '-uploaded_at'], name='uploaded_im_user_id_c96ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadedimage',
            index=models.Index(fields=['status'], name='uploaded_im_status_578880_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['-confidence_score'], name='analysis_re_confide_33522d_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisresult',
            index=models.Index(fields=['is_suspicious'], name='analysis_re_is_susp_883ec1_idx'),
        ),
    ]
